### ISSUE TITLE
Create JScholarship transition plan and requirements

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#19]
* Do we need to use aliasing to create handle-based URIs like JScholarship?
* Do we keep JScholarship records alive?
* Will the system acquire jscholarship's domain name when the migration process is done, so that existing URIs into JScholarship still work?  Redirects?
* Do we need to update links in ASpace away from JScholarship to the new i8 setup?

**Comment by birkland** [comment]
JScholarship uses handles to address items, but in the process of dereferencing a JSchollarship URI, is there a handle lookup involved?  Or do we just use parts of the handle ID to mint unique URIs?

**Comment by htpvu** [comment]
Per email titled “Answers”, dated “Wednesday, April 22, 2020 at 5:17 PM”: Both existing JHU IR uris and the Item handle uris are persistent and need to be resolvable.

**Comment by htpvu** [comment]
Do we need to use aliasing to create handle-based URIs like JScholarship? NO
Do we keep JScholarship records alive? NO
Will the system acquire jscholarship's domain name when the migration process is done, so that existing URIs into JScholarship still work? Redirects? System will also named JScholarship, but dont know about domain name.
Do we need to update links in ASpace away from JScholarship to the new i8 setup? NO

**Comment by emetsger** [comment]
Summary of where we are to-date is [here](https://github.com/jhu-sheridan-libraries/iDC-general/issues/42#issuecomment-648287529)

**Comment by htpvu** [comment]
new system is called Hopkins Digital Library. Domain name [digital.library.jhu.edu](http://digital.library.jhu.edu/)
