### ISSUE TITLE
Research how to show Collections over items regardless of relevance

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#233]
iDC-7, iDC-30

iDC-7: Normal Path: Step 9b

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by birkland** [comment]
follow-up question:  Is this still relevant?

**Comment by noahwsmith** [comment]
Maybe the results can be grouped in Solr before they are returned?
https://solr.apache.org/guide/7_1/result-grouping.html

And if not, then maybe check into weighting somehow?

Or handle as a post-process on the JS side?

**Comment by birkland** [comment]
This should not block launch

**Comment by jaredgalanis** [comment]
labeling UI because it seems like a potential solution would involve the UI sending solr a field to sort on.

**Comment by jabrah** [comment]
* Looks like we can have a configuration level change that sorts results by type (Collection Object, Repository Item) by adding a new sorting parameter in the config of the REST Export view

![image](https://user-images.githubusercontent.com/5167587/132396272-21aea333-5edc-4507-a923-1642a064bd04.png)

It seems like this would group by type, unless another `sortBy` parameter is selected by the user, in which case, type would be ignored when sorting. Sorting by type could then be restored by clearing the option, or selecting an appropriate option, assuming the option is added to the UI. The upside of this is its ease of implementation and the fact that "group by type" is sort of user togglable. However, the user will not be able to sort by BOTH type and title, for example.

* Solr results grouping is an interesting feature that would take more development work. When working, it would allow the separation of sorting and "group by type." The current search interface is driven off the Solr REST Export view and I'm not sure if the serializer used in the REST Export would be able to handle the different JSON structure that's returned when using results grouping

* Client side post-processing to group results wouldn't work because of paging

**Comment by jabrah** [comment]
`/admin/config/search/search-api/index/default_solr_index/processors` : Managing processors for Solr indexing has a **Type-specific boosting** Option that will let us set custom boost values for different entity types and taxonomies.

![image](https://user-images.githubusercontent.com/5167587/132403014-487135c8-552b-4c65-bf45-9c49f23e7b9f.png)

This may be satisfy the use case

**Comment by jabrah** [comment]
Note, Solr allows simply having multiple sorting parameters. However, in our case, since we're passing the search through the REST Export endpoint, we would not be able to use the `sort_by` parameter that we already use, since this parameter is interpreted by the this endpoint. It might be possible to append an extra raw Sorl sort parameter to the query parameter, which is passed to Solr unprocessed, but this is less than ideal
