### ISSUE TITLE
Decide how to handle the ingest of binaries (blocked by S3 PR)

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#243]

**Comment by emetsger** [comment]
Private storage is to be used to store binaries.  

Because S3 is sufficiently abstracted from migrations (S3 work provides an implementation of the `private://` file storage scheme), migrations can simply use whatever methods are required to download files and place them in `private://` storage.

Likely this will mean using something like the `file_import` migration process plugin to download binaries, and create directories in the `private://` storage organized by YYYY-MM-DD or something like it.

Stakeholders will be able to put their binaries wherever they wish, as long as the URLs are able to be viewed publicly.  (Migrations do have some capability for performing authentication when retrieving binaries if we need to go that route).
