### ISSUE TITLE
investigate options for enabling sending emails from iDC ui

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#266]
This would be part of the support for use case iDC-10 https://docs.google.com/document/d/16JCMBTGlr1NQwh9tAxz28aAPxMyKuUHNBW-h2H9yjOc/edit 
and iDC-15 https://docs.google.com/document/d/1g7jWBsgcu7-NGV3aK1vPEhCxWtHu0sCCptUwNrTG3bM/edit

the UI portion to support these use cases has proceeded independently of this work. May or may not have been finished and ready to integrate. 

Expected outcome: executable work plan (with time estimates) for enabling iDC application to send email from the UI.

**Comment by birkland** [comment]
Elliot is scoping this ticket, figuring out what is done on the UI side, what needs to be done on the backend size.  This originally had a vendor tag.  Once we have a good idea of what needs to be done, see if it's appropriate for Ellot to follow through, or assign to vendor

**Comment by emetsger** [comment]
### Overview
* Drupal has been updated to support the sending of email using SMTP, the PR is [here](https://github.com/jhu-idc/idc-isle-buildkit/pull/63).
  * As an alternative to SMTP, Born Digital recommended the use of the [SendGrid](https://sendgrid.com/) service, which is supported by Drupal upon installing and configuring the [sendgrid-integration](https://git.drupalcode.org/project/sendgrid_integration) module.   I did not explore this option deeply, chiefly because of time, but secondarily it adds a dependency on an external service, which, to the former point, would increase the due diligence with respect to understanding the implications/consequences.  I'm not against SendGrid, but SMTP wiring was easy and let me move forward.
* There are couple of issues that will ultimately need to be accounted for.  For example, the administrative email addresses used by Drupal will need to be updated with valid JHU email addresses.  This ticket doesn't address or describe those issues, but it essentially boils down to updating Drupal configuration with valid "admin" email addreses.
* The primary and most urgent issue is that with the advent of a [working SMTP configuration](https://github.com/jhu-idc/idc-isle-buildkit/pull/63), emails sent by Drupal using the [contact module](https://www.drupal.org/docs/8/core/modules/contact/overview) are, from the recipient's standpoint, intelligible.  Emails produced by the Contact Module arrive in the recipient's inbox containing HTML markup, but the markup is rendered as plain text, thereby obscuring the information content of the email message.   

So the primary focus is to provide a fix or workaround for the intelligible email bodies send by Drupal via the contact module.

### To Replicate
You will need:
1. The images from https://github.com/jhu-idc/idc-isle-buildkit/pull/63.  As of this writing, the image tag to use is `upstream-20200824-f8d1e8e-49-g27324f1` (e.g. the value of `TAG` in `.env`).
2. A working SMTP configuration.  I used GMail with my personal account, but feel free to configure something else.  In order to use GMail, you need to 1. Have a GMail account 2. Enable MFA (a.k.a. "[2-step verification](https://devanswers.co/enable-2-step-verification-google-account/)") 3. Generate a GMail [app password](https://security.google.com/settings/security/apppasswords).  With your GMail app password in hand, emend `.env` and add the following configuration:
```
DRUPAL_SMTP_ENABLE=true
DRUPAL_SMTP_VERBOSE=true
DRUPAL_SMTP_AUTH_PRINCIPAL=yourgmailaddress@gmail.com
DRUPAL_SMTP_AUTH_TOKEN=gmailapppassword_no_spaces_or_dashes
DRUPAL_SMTP_FROM_ADDRESS=webmaster@library.jhu.edu
DRUPAL_SMTP_RELAY_HOST=smtp.gmail.com
```
3. If https://github.com/jhu-idc/idc-isle-buildkit/pull/63 _has not been merged_, you will need to edit `docker-compose.env.yml` and edit the `environment` for the `drupal` service, appending the following environment, re-generate `docker-compose.yml` (`make -B docker-compose.yml`):
```
DRUPAL_SMTP_ENABLE: ${DRUPAL_SMTP_ENABLE}
DRUPAL_SMTP_AUTH_PRINCIPAL: ${DRUPAL_SMTP_AUTH_PRINCIPAL}
DRUPAL_SMTP_AUTH_TOKEN: ${DRUPAL_SMTP_AUTH_TOKEN}
DRUPAL_SMTP_FROM_ADDRESS: ${DRUPAL_SMTP_FROM_ADDRESS}
DRUPAL_SMTP_RELAY_HOST: ${DRUPAL_SMTP_RELAY_HOST}
DRUPAL_SMTP_VERBOSE: ${DRUPAL_SMTP_VERBOSE}
DRUPAL_SMTP_TLS_VERSION: ${DRUPAL_SMTP_TLS_VERSION}
```
4. Perform `make -B docker-compose.yml` to update `docker-compose.yml` with the updated `.env`.
4. Bring the stack up, or if it was already up, restart it so the new image tag and SMTP environment is picked up by the container.  To verify this, `docker-compose exec drupal env |grep SMTP` should return the expected values.
5. Verify that the SMTP plumbing works by obtaining an interactive PHP shell in the `drupal` container, while tailing the logs in another terminal `docker-compose exec drupal php -a -c /etc/php7/php.ini`.
6. Send yourself a test email by execute the `mail` function: `mail('yourgmail@gmail.com', 'Test Subject', 'Test Message Body');`.  Verify the SMTP exchange was successful in the `drupal` logs, and see that the message arrives in your inbox.

---

Now that you've verified SMTP plumbing is working in Drupal, you can begin to debug the Contact Mail issue described earlier.

1. Identify or create a `collection_object` that has your email address as the value for `field_collection_contact_email`.  You can do this by editing an existing collection:
![image](https://user-images.githubusercontent.com/146970/130845886-61d14f13-8117-469e-867c-f1961cbd4e0f.png)
2. Next, view the collection, and click on the "Ask the collection admin" button, fill out the form and submit it.
<img width="1162" alt="moo" src="https://user-images.githubusercontent.com/146970/130846602-8ab8dd62-0e63-497f-830e-9233387c34af.png">
3. Monitor the `drupal` log and see that the SMTP exchange successfully occurs.

4. Check your inbox for the mail.
5. If you receive two or more emails, it is probably because there are [_two_ contact emails configured](https://islandora-idc.traefik.me/admin/structure/contact/emails).  Disable the duplicate, as it will interfere with your tests.
6. At this point you should be able to observe the malformed email message body reliably.
7. [This document](https://docs.google.com/document/d/1IRyHOeHVojHaNN3voARhw4Pp0zYKzikwn3NIpE03Wso/edit#) attempts to describe the work done so far to identify why the issue happens and under what conditions.  It also identifies a potential workaround, though the workaround is sub-optimal (as most are).

**Comment by emetsger** [comment]
Note that if you'd like to use a PHP debugger, you can take the following steps:
- Edit `docker-compose.minio.yml` and update `minio` to listen on some other external port besides `9000`, or even delete the line.  Minio does not need to be accessible externally.  The goal is to free up port `9000` so it can be used by your debugger.
- Run `make dev-up`

Have your debugger listen for XDebug connections and install a browser plugin to trigger the debug session, this is covered with a bit more detail [here](https://github.com/jhu-idc/idc-isle-dc#debugging).
