### ISSUE TITLE
Categorize taxonomy terms and how to manage them

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#294]
Taxonomy values can be treated in two possible ways:
1. As site-local data; modified or added to regularly as part of the daily operation of IDC (e.g. the Subject taxonomy, or Person). 
2. As centrally-managed "foundational" values that are expected to be provided by "the system", and are expected to be present, identically, in every IDC instance (from the development environment, through production) 

For each known taxonomy, come to an agreement with the stakeholders on how these taxonomy data will be managed.  If any taxonomies are in category (2), then we will need to figure out change management:  How are taxonomy values propagated between systems whenever new ones are added?  Create a new ticket to for solving this question, if relevant taxonomies are identified.

**Comment by emetsger** [comment]
The current expectation from a migration perspective is that taxonomies are managed by an IDC global admin or a user with some kind of administrative role.  Migration definitions are currently defined and tested for all "user-land" taxonomies, e.g. Subject, Person, Corporate Body etc.  "System" taxonomies like Islandora Model do not have supported migrations, and are expected to be seeded with foundational data.

From this perspective, it would be the responsibility of an IDC admin to seed and maintain the "user-land" taxonomies (either using IDC interactively via the admin UI, or by using the Migrate Source UI module), and the role of the "system" to provide taxonomies for system taxonomies like Islandora Model and their ilk.

**Comment by htpvu** [comment]
Expected outcome: documentation on the categories and their management requirements

**Comment by bseeger** [comment]
### Taxonomy access by role (as defined by stakeholders)

Collection Level Admins can add and edit terms in the following Taxonomies: 
- Access Rights
- Copyright and Use
- Corporate Body
- Family
- Genre/Form
- Geographic Location
- Language
- Person
- Resource Types
- Subject

Global Admins can add/edit/delete terms in the following Taxonomies: 
 - All of the above
 - Islandora Access - this taxonomy is used to group admins into collections, so the GA has to have access to it.  It is Global Admin-land data. 

Drupal System Admin Level (add/edit/delete/change configuration): 
 - All of the above
 - Islandora Display
 - Islandora Media Use
 - Islandora Models

The last three I would consider foundational (#2 above) and the system won't operate well if they don't have some terms in them upon startup. 

### Other foundation data that's not part of a taxonomy
Another piece of foundational material is of the entity type `contact_email` and is used by the contact page setup to email a person.  It is considered content (versus config) and also foundational, since if it doesn't exist the contact page will not work correctly.

**Comment by emetsger** [comment]
Is there a shared understanding that it is OK for the following to _not_ have migration definitions:
- Islandora Access
- Islandora Display
- Islandora Media Use
- Islandora Models

That is to say, as migrations stand right now, a Global Admin or a Drupal System Admin wouldn't be able to modify the content of those taxonomies using migrations.  I just want to make sure we're on the same page (these migrations could be added if they are needed but right now they don't exist since they are typically small taxonomies that won't be edited much).

**Comment by bseeger** [comment]
The work I'm doing involves the global admin using the Islandora Access taxonomy regularly and will most likely need a migration.  I actually created one for it so I could easily import some stuff.   I was going to add a test for it, too.

**Comment by bseeger** [comment]
@emetsger  - I can hold off on writing a test for that taxonomy if you'd rather do it.

**Comment by emetsger** [comment]
@bseeger no problem, go for it!

**Comment by emetsger** [comment]
@bseeger I just wanted to insure everyone was on the same page with respect to what has "migration coverage" and what doesn't and if you'd like to take on adding that particular one that's no problem with me.  There's plenty to do...

**Comment by bseeger** [comment]
@htpvu  - I created this file to document this and describe the roles of the various taxonomies in our Islandora system as well as who is expected to manage each one. 

https://docs.google.com/document/d/1DV3_f63IGjfydRKKWBXDx09mHCyHmECKYJ8zWY2ev7M/edit#

**Comment by htpvu** [comment]
the remaining work:
- review and ratification with stakeholders (Michelle, Katie) --> close ticket after sign off
- notes and description change management (how change could be made: via migration or module update, etc?) --> to be split into its own ticket. could be done after launch

**Comment by htpvu** [comment]
Katie had ratified the associated document via email.
