### ISSUE TITLE
Drupal file download expose bare links; provides no content disposition, media type, or meaningful file names

### ISSUE THREAD

**Issue by emetsger** [jhu-idc/iDC-general#311]
When downloading files from Drupal (e.g. any File that might be attached to Media), they are presented to the browser with no meaningful media type (e.g. application/octet-stream), no content disposition, and the file names are simply the name of the bytestream from the Drupal public file system.

![image](https://user-images.githubusercontent.com/146970/113792899-05106500-9715-11eb-973b-30468d855a8b.png)

This is troublesome from a usability perspective: the user has no way to interact with the file until it is downloaded and renamed with an appropriate extension (which is at best annoying and at worst a handicap - how many people would know which extension to put on an image file when there is an alphabet soup of potential candidates - .png, .jp2, .jpg, .jpeg, etc etc).

Secondly, this implies that Drupal does not mediate the exchange of binary data with the browser which would mean that there is no mechanism to secure the file content.  By and large, it's anticipated that Drupal will be housing public data, so authorization to content isn't the highest priority, however we do have usecases (and perhaps legal obligations) to prevent copyrighted material (e.g. some Levy content is under copyright) from being downloaded by the general public.

A solution would require some sort of intervention by Drupal to mediate the exchange of content between the user and the system, potentially requiring an authorization check before handing out the bytes.  The same intervention could/should also provide meaningful filenames and media types to the user.

(Note this issue came about from the implementation of [media migrations](https://github.com/jhu-idc/idc-isle-dc/pull/95))

**Comment by bseeger** [comment]
We have the requirement of some files being restricted, so having the direct download path for any file accessible isn't going to suite our use case, since a user can bypass our restrictions this way.   The use case is that there will be a link/button/dropdown on a repository items page through which a user can download the file of their choosing.   We may still have the same mediation problems, but I think this ticket's particular path to downloading files should be forbidden.

**Comment by birkland** [comment]
FYI,  I've successfully enabled S3fs in conjunction with the private filesystem.   Here are the headers returned from example content ingested by the File migration tests:
```
curl -I https://islandora-idc.traefik.me/system/files/a7/01/85/5dfddfde4ccfaf9a976ac524f268231694
HTTP/2 200
accept-ranges: bytes
cache-control: private
content-language: en
content-type: image/jpeg
date: Mon, 19 Apr 2021 16:23:31 GMT
expires: Sun, 19 Nov 1978 05:00:00 GMT
last-modified: Mon, 19 Apr 2021 16:20:03 GMT
server: nginx
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-generator: Drupal 8 (https://www.drupal.org)
x-powered-by: PHP/7.3.27
x-ua-compatible: IE=edge
content-length: 7584545
```
Notably:
* the media type _is_ set correctly
* the file name is not present in Content-Disposition or the URL
* Inherent in being on the private filesystem, all access is mediated by Drupal, instead of nginx or s3.  By default, all content is accessible to everybody (i.e. drupal proxies it, but has no access restrictions in place)
* cache control is `private` and expiration is in 1978 (inherently expired), which could be problematic in practice.

**Comment by emetsger** [comment]
> Here are the headers returned from example content ingested by the File migration tests

Did you alter the migration definitions to use the `private://` filesystem, or were the stock migration definitions used?  Or does s3fs simply take over `public://` and by doing so it assumes the characteristics of a private fs?

> the file name is not present in Content-Disposition or the URL

This should be trivial to fix.  The mime type is accessible to the download controller, so that means other attributes, like `filename` should be available to the controller.  We will need to insure the the media migrations are mapping the correct field from the source spreadsheet to the `File`s `filename`.

**Comment by birkland** [comment]
Yes, I changed the migration definitions to use `private://`.   When s3fs implements `public://`, accesses are _not_ proxied.  This is analogous to where the out-of-the-box `public://` fs-based implementation presumes a web server is serving the directory (and Drupal just mediates the uploading).   With s3fs taking over  `public://` Drupal simply provides links directly to s3 for download, and mediates the upload.

**Comment by birkland** [comment]
Oh hold, need to re-evaluate based on consequences of https://github.com/jhu-idc/iDC-general/issues/310

**Comment by birkland** [comment]
Review of current functionality reveals that this is no longer an issue.
