### ISSUE TITLE
 Assess  the effort impact of the decision on resource references

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#316]
Assess what it takes to implement the decisions from the URI/LocalIds meeting (relating to migration relationships). The decision is documented here https://docs.google.com/document/d/1WCu8bRtLELgGGoIBuyed0-pJB1GwgPuuGeLnMbCOaMM/edit#heading=h.dwao6437w2vq

The outcome of this ticket is a chosen approach for implementing the decision and an estimate of effort it would require.

**Comment by emetsger** [comment]
### Issue Summary
To illustrate the issue, here is a Migration plugin configuration which assigns a value to the field 'Subject' on an Islandora Object, elided for brevity (see `config/sync/migrate_plus.migration.idc_ingest_new_items.yml`):
```yaml
  field_subject:
    - plugin: skip_on_empty
      ...
      source: subject
    ...
    - plugin: entity_lookup
      bundle_key: vid
      bundle: subject
      entity_type: taxonomy_term
      value_key: name
```

The value from the spreadsheet column `source` references an existing taxonomy term in Islandora by name, e.g. 'History'.  The plugin configuration above takes the name of the taxonomy term from the spreadsheet ('History') and looks up the Drupal entity for the named term.  The reference to the entity is stored on the `field_subject` field of the Islandora Object.

However, the 'Subject' on an Islandora Object is allowed to reference a number of different taxonomies (see `config/sync/field.field.node.islandora_object.field_subject.yml`):
```yaml
    target_bundles:
      corporate_body: corporate_body
      family: family
      geo_location: geo_location
      person: person
      subject: subject
```

The value from the spreadsheet column `source` should be able to reference an existing taxonomy term in the `Family`, `Geographic Location`, `Person`, or `Subject` taxonomies, but the configuration of the `entity_lookup` plugin prevents this by limiting lookup to the Subject taxonomy.

### Proposed Solution
In the URI meeting we decided to [pursue a convention](https://docs.google.com/document/d/1WCu8bRtLELgGGoIBuyed0-pJB1GwgPuuGeLnMbCOaMM/edit#bookmark=id.17spgbslmuf0) that would require the spreadsheet value to specify the taxonomy _and_ term name.  So instead of the value being e.g., `History`, the group recommended using `subject:History` instead.

### Implementation
To implement this solution, I recommend that we develop a new Migration plugin.  At a high level the new plugin will:
1. Parse the value from the spreadsheet (e.g. `subject:History`) into its component parts
2. Use those component parts to configure an instance of the `entity_lookup` plugin
3. Invoke the `entity_lookup` plugin

When exploring this approach, including "future-proofing" the use of the plugin, I recommend that each parameter of the entity plugin be represented in spreadsheet values.  The original recommendation (e.g. `subject:History`) would formally be:
* `<taxonomy machine name>`:`<value of taxonomy 'name' field>`

However, I think it is going to be best to recommend that _all_ the fields of the `entity_lookup` plugin be encoded in the spreadsheet value:
* `<entity type>`:`<bundle key>`:`<bundle name>`:`<bundle field>`:`<value>`

The revised recommendation would change `subject:History` to `taxonomy_term:vid:subject:name:History`.  The former is much easier to type, while the latter is far more cumbersome.  To address this, the new plugin will allow default values for all of the fields to be specified.  This would allow `taxonomy_term:vid:subject:name:History` to be written as `::subject::History` (note that the colons used to separate the fields _must_ be present, even if a value is not).  Empty values will be supplied by configuration, rather than coming from the spreadsheet.

This would allow the field 'Subject' on an Islandora Object to reference any of the allowed taxonomies from its field definition.  For example (assuming there are defaults for `<entity type>`, `<bundle key>`, and `<bundle field>`), these would all be valid values for an Islandora Object Subject:
* `::subject::History`
* `::geo_location::Mt. Everest`
* `::family::McCoy`
* `::person::Ansel Adams`
* `::corporate_body::Enron`

If the defaults need to be overridden, simply add them to the value.  This might be an example where the entity is looked up using the value of a fictional `lat_log` attribute of a Geographic Location instead of its name.
* `::geo_location:lat_long:27.9881N,86.9250E`

A note about the use of colon as a delimiter: the delimiter used is specified by the plugin configuration.  If the delimiter appears in the value, then it will need to be encoded.  A simple encoding scheme using "percent encoding" is recommend.  For example, if you need to look up a Subject whose name was `My Subject: it contains a colon`, then you'd specify it in the spreadsheet as: `::subject::My Subject%3A it contains a colon`

### Effort Estimate
Initial exploration indicates that the proposed approach is viable.  Using the Drupal APIs to create an instance of `entity_lookup` plugins on demand, parameterized by values from the spreadsheet is doable.  The unknown is how complicated testing may become, since the Drupal dependency injection framework is used (the DI aspects would need to be accounted for in tests).

Three days of dedicated effort should be enough, assuming that testing goes smoothly.

The only places this new plugin must be used is on fields that allow for multiple taxonomies.  Other fields can continue to use the regular `entity_lookup` plugin.

**Comment by birkland** [comment]
Out of curiosity, what is "bundle key" and what sort of information does it convey?  For example, in `taxonomy_term:vid:subject:name:History`, what is "vid", and where does it come from?  Would there possibly exist some "foo" such that `taxonomy_term:vid:subject:name:History` is distinct from `taxonomy_term:foo:subject:name:History`?

**Comment by bseeger** [comment]
I'm trying to think of a use case where we'd want to use another field in the taxonomy to key off of.  Do you have a sense of when we'd need this?   Also, if we keyed off another field and it wasn't unique, could this handle getting a few values back?  (I realize as I say this that `name` may not be unique, but in theory they should be unique w/in a taxonomy, it's just not enforced).

**Comment by bseeger** [comment]
With this particular setup, would it be easier to use this type of above setup with member_of relationship?  Or rather, does this make it easier to populate that field as well? 

`node:vid:islandora_object:title:A great title`

**Comment by emetsger** [comment]
> Out of curiosity, what is "bundle key" and what sort of information does it convey?

This vid is the field in the `taxonomy_term` entity that conveys the entity id used.  It is specific to the entity type.

**Comment by emetsger** [comment]
> I'm trying to think of a use case where we'd want to use another field in the taxonomy to key off of

Language code and language name is an existing example where a single taxonomy entity could be looked up by different keys.

The writeup supplies additional contrived, but feasable, example related to latitude and longitude lookup of a geographic location term.

**Comment by emetsger** [comment]
> Also, if we keyed off another field and it wasn't unique, could this handle getting a few values back?

No, it would not.  This plugin simply delegates to the `entity_lookup` plugin, and returns what the `entity_lookup` plugin returns (or throws). The user is still responsible for insuring that it returns a single value.

**Comment by emetsger** [comment]
> Would there possibly exist some "foo" such that `taxonomy_term:vid:subject:name:History` is distinct from `taxonomy_term:foo:subject:name:History`

Short answer: no.

There is a possibility that `taxonomy_term:vid:subject:name:History` _would_ be distinct from `bar_entity:foo:subject:name:History` (where `foo` is the field on `bar_entity` that contains the entity id)

**Comment by emetsger** [comment]
> With this particular setup, would it be easier to use this type of above setup with member_of relationship?

This plugin could be used in lieu of `entity_lookup` in any migration, for any field, provided the value in the spreadsheet follows the format described above.

**Comment by bseeger** [comment]
> This plugin could be used in lieu of entity_lookup in any migration, for any field, provided the value in the spreadsheet follows the format described above.

^^  Nice - that's pretty handy.   

Separately, I'm wondering - do you think it could drop `bundle key`?   From what I can find the values would be nid, vid, type, uuid, langcode, but I'm not sure I got that from the right places (that was the fields on it in the DB, since drupal docs don't really talk about it).  Do I have the right keys?  If so, maybe 99.9% of the time we'd use vid?  The truncated examples mean you don't have to specify it unless you need it, but we'd still have to explain what the empty part means to users in documentation.

**Comment by birkland** [comment]
Yeah, I've been having trouble understanding what bundle key means, and how I (or a librarian) would try to conceptualize it.  From my understanding now, there is exactly one correct value for any a given entity type.  If that can be made an implementation detail that doesn't bleed into the "API" of CSVs (i.e.  if refs can be simplified to `entity_type:bundle_name:bundle_field:value`) then we ought to do it.

**Comment by emetsger** [comment]
I'm ambivalent about dropping the bundle key from the "api".  It's a required field of the entity_lookup plugin.  It functions exactly the same as all the other fields.  It will almost always be elided by default configuration.  But, as with all the other fields, it may be overridden if supplied.

The cost is an extra `:` on the part of the user.  If this is something that is super important, and we think that it's going to tax the users so much that it can't be included in documentation, we can take it out.  It is more likely to tax programmers more: oh right, the specification isn't uniform. It doesn't treat all of the keys equally.  One is different than all the rest.   It's _uniform_, it's _simple_, and the cost on the part of the user is negligible.

**Comment by emetsger** [comment]
After having a think on this, the bottom line is that it is no extra effort, really, to implement any of the possibilities:
* `<taxonomy machine name>:<value of taxonomy 'name' field>`
* `<entity type>:<bundle key>:<bundle name>:<bundle field>:<value>`
* `entity_type:bundle_name:bundle_field:value`

I've fallen prey to something I've been critical of in this project, which is one of "expanding" or "scope creep": adding in extras or going further with an implementation than what was called for by stakeholders.  This ticket wasn't meant to engender a thread of discussion, but it is a useful reminder.

If folks agree, I'll plan on implementing `entity_type:bundle_name:bundle_field:value`, which eliminates the `vid`.  If that implementation ends up being too much "cognitive load" for stakeholders or for us, then it will be easy to change in a subsequent PR.

**Comment by bseeger** [comment]
That all sounds good to me.   That's good to know that the effort for each option is pretty much the same, too.  I had been wondering if more qualifiers meant more work, but it doesn't sound like it.
