### ISSUE TITLE
Security and production-readiness audit

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#353]

**Comment by GervaisdeM** [comment]
@birkland 

I'd love to dive into this ticket.

I apologize if this has been shared already and I have missed it. Is there documentation about the planned configuration for the production environment that can be shared with me/us?

Is production up and running already in a stage sort of setup that we can look at? Is it possible to get access (read only would be fine) to the AWS account where the production environment is set up?

**Comment by birkland** [comment]
Let me ping @derekbelrose and @jhujasonw who'd be able to set you up with any sort of information or access you'd need on the cloud environments.  At this point, the production environment isn't set up yet, but we do have a test instance (test.digital.library.jhu.edu) and stage (stage.digital.library.jhu.edu).  I think all cloud environments ought to be equivalent for your purposes - the only real configuration difference between them is administrative in nature (hostnames and associated config, different SAML certificates to reflect their different hostnames, etc).  

For the sake of security and production-readiness audits, I think the significant areas of concern are:
* instance-specific environment variables (which configure passwords, certs, hostnames, etc)
* Drupal configuration (in source control at [jhu-idc/idc-isle-dc/codebase/config/sync](https://github.com/jhu-idc/idc-isle-dc/tree/development/codebase/config/sync), and [local.settings.php](https://github.com/jhu-idc/idc-isle-dc/blob/development/codebase/web/sites/default/settings.local.php))
* Drupal modules in composer.json and [composer.lock](https://github.com/jhu-idc/idc-isle-dc/blob/development/codebase/composer.lock)
* Other stack services, such as solr, cantaloupe, etc.  The images for these reside in [jhu-idc/idc-isle-buildkit](https://github.com/jhu-idc/idc-isle-buildkit)
* The cloud/kubernetes topology (e.g. networks, volumes, proxies, load balancers)

Assembling actual documentation from our set of working docs is a big TODO.  But here are a few resources that might be helpful getting started:
* [cloud topology diagram in this working doc, page 3](https://docs.google.com/document/d/1DH3jAlh2E0doo6UG3cCTxbvIwnMapad8SkxUsMOyRns/edit)
* [stack summary](https://docs.google.com/document/d/1RXeTGBw0Ftjbf6gaFmMJBxN6g9YzqryL4apWEoi2rwk/edit)
* [system diagram](https://lucid.app/lucidchart/invitations/accept/inv_8f70c1e1-768b-4ee6-a391-d652ed1535c4?viewport_loc=-1575%2C-1516%2C1513%2C1356%2C0_0)
* Drupal [startup script](https://github.com/jhu-idc/idc-isle-buildkit/blob/main/drupal/rootfs/etc/cont-init.d/99-custom-setup.sh#L121-L173)
* If it helps, a link to the [kubernetes repository](https://github.com/jhu-idc/idcApp-k8s), containing or k8s manifests.  These define the deployments in the cloud environments.

Let me know what else you'll need.  Jason or Derek can let you know how to access the various bits and pieces of the AWS infra.

**Comment by derekbelrose** [comment]
@GervaisdeM are you asking for information or direct access to our cluster?

**Comment by GervaisdeM** [comment]
@birkland Thanks for the info dump!
I'm being asked to triage the ticket and set times on how long it will take me to do it and the ticket was sparse on info. :)

@derekbelrose I'm asking for both if possible. I'm happy to start with documentation.

**Comment by derekbelrose** [comment]
@GervaisdeM We (@jhujasonw  and myself) will assume responsibility for the Kubernetes cluster and AWS account security. @birkland should be able to confirm this, but I believe we are hoping that you and your team can lean on your extensive Drupal and Islandora expertise to audit the software and configurations that are provided by the ISLE project as well as the modifications made by DRCC.

**Comment by GervaisdeM** [comment]
Thanks all for the clarifications and information on this ticket.
🙂

**Comment by birkland** [comment]
@GervaisdeM  Sorry, I think there may have been a miscommunication somewhere.  From the outset, Stephen Perkins mentioned that security and production-readiness audits were one of DGi's core competencies, but did not define in detail exactly what they entailed.  So we've been coming at this from the perspective that you know what comprises the kinds of audits you do, but you are less familiar with containerized environments, so the key to such an audit's success will be translating your standard audit checklist to a containerized Islandora stack.  So.. if you provide a list of what comprises your audits, we can help point out to where and how to perform the steps.  I'm a bit worried that containerization is starting to prove to be too much of a barrier, but we'll see how this progresses.

As far as my comments in https://github.com/jhu-idc/iDC-general/issues/353#issuecomment-859651980, those bullet points represent the entirety of the areas of concern that I'm aware of - it's possible you may be aware of more.  As Derek mentioned, our operations folks have decided that it's likely not worth your time to audit the implementation details of the infrastructure in AWS.  As far as I understand, then, that would leave these bullet points:
* instance-specific environment variables (which configure passwords, certs, hostnames, etc)
    * I'm not sure ho much you can do here, other than comment on "make sure this is set to this kind of value"
* Drupal configuration (in source control at jhu-idc/idc-isle-dc/codebase/config/sync, and local.settings.php)
* Drupal modules in composer.json and composer.lock
* Other stack services, such as solr, cantaloupe, etc. The images for these reside in jhu-idc/idc-isle-buildkit

Thus, would you agree the work implied by this ticket is a function of how your standard audit checklist applies to those above bullet points?

**Comment by DonRichards** [comment]
This is going to seem like a bit of rambling and all over the place. I'm only filling in what I see might be security target gaps from previous comments.

Just adding to the "other services" reference, there are URLs you don't want people to have direct access to like Solr's admin console or cantaloupe's management UI. Knowing these URLs and limiting direct access entirely on production and limiting access on Staging is probably a wise approach. Not all of these service are on different ports or subdomains, so this might need some customization to the settings.php file specific to the production environment or at a higher level in the routing service. Solr's admin console does not require a login to make breaking changes. So identifying the end points and verifying they access limitations is critical to securing the system. 

Keep in mind that "traditional" security models are no longer valid with containerized environments. But even with that said backups are still an important aspect of data integrity and are typically part of a security model. Backup are to protect again a point of failure. Food for thought, can you recover the site if a trusted admin's AWS login was compromised and all of the volumes were purged? I highly recommend taking this situation into consideration when planning out the backup process. AWS may feel like magic but there are instances where AWS data recovery wasn't possible and failed the AWS client. [For instance](https://www.linkedin.com/pulse/cloud-migration-has-risks-too-bal%C3%A1zs-gunics). And another [Amazon shows why you shouldn’t put all your tech eggs in one cloud basket](https://www.computerworld.com/article/3176691/amazon-shows-why-you-shouldn-t-put-all-your-tech-eggs-in-one-cloud-basket.html). My suggestion is to diversify your backups. Look up Multicloud options or an in-house solution to backup the servers (not just preservation material).

So that everything is commented on, Docker provides a "[Docker Security](https://docs.docker.com/engine/security/)" page that provides additional comments on hardening the host system and docker security features. Worth reviewing at this stage to see if anything was missed.

I hope this is helpful.

**Comment by htpvu** [comment]
the work on this has been done.
