### ISSUE TITLE
Set the resuse parameter to true for Files in existing migrations

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#377]
The resolution for #310 involves setting `reuse` to `true` in all existing migrations involving `File` entities.  

As per Elliot:
> We need to change the value of the parameter, which I think will impact tests (the behavior of the reuse parameter is documented by at least one test), so the test will need to be updated

**Comment by bseeger** [comment]
Tangential, but still important, note:  the [migrate_file](https://www.drupal.org/project/migrate_file) plugin uses error codes that are deprecated and will be pulled out of 9.0.0.  (https://api.drupal.org/api/drupal/core%21includes%21file.inc/8.8.x)

> /**
> * Flag for dealing with existing files: Appends number until name is unique.
> *
> * @deprecated in drupal:8.7.0 and is removed from drupal:9.0.0.
> *   Use \Drupal\Core\File\FileSystemInterface::EXISTS_RENAME.
> */
> const FILE_EXISTS_RENAME = FileSystemInterface::EXISTS_RENAME;

and 

> /**
>  * Flag for dealing with existing files: Appends number until name is unique.
> *
> * @deprecated in drupal:8.7.0 and is removed from drupal:9.0.0.
> *   Use \Drupal\Core\File\FileSystemInterface::EXISTS_RENAME.
> */
> const FILE_EXISTS_RENAME = FileSystemInterface::EXISTS_RENAME;

**Comment by bseeger** [comment]
I can't get this to work.  This has no effect on creating only a single File for a file:

```
  field_media_document/target_id:
    plugin: file_import
    source: '@_download_filepath'
    move: true
    reuse: true
    rename: false
    id_only: true
    destination: '@_destination_drupalpath'
    mimetype: mime_type
    filename: name
```

Digging deeper, this check happens: (https://git.drupalcode.org/project/migrate_file/-/blob/2.0.x/src/Plugin/migrate/process/FileImport.php#L222) 

```  
// If we're in re-use mode, reuse the file if it exists.
    if ($this->getOverwriteMode() == FILE_EXISTS_ERROR && $this->isLocalUri($destination) && is_file($destination)) {
      \Drupal::logger("reuse bug")->info("We are in reuse mode now");
      // Look for a file entity with the destination uri.
      if ($files = \Drupal::entityTypeManager()->getStorage('file')->loadByProperties(['uri' => $destination])) {
        // Grab the first file entity with a matching uri.
        // @todo: Any logic for preference when there are multiple?
        $file = reset($files);
        // Set to permanent if the file in the database is set to temporary.
        // This means that the file was probably set to be removed during
        // garbage collection, which we don't want to happen anymore since we're
        // using it.
        if (!$file->isTemporary()) {
          $file->setPermanent();
          $file->save();
        }

        return $id_only ? $file->id() : ['target_id' => $file->id()];
      }
      else {
        \Drupal::logger("reuse bug")->info("We are NOT in reuse mode now");
        $final_destination = $destination;
      }
    }
```

The `isLocalUri()` fails, and this code isn't run.  Some debug:

```
    $local = $this->isLocalUri($destination) ? "true" : "false";
    \Drupal::logger("reuse bug")->info("overwrite mode: " . $this->getOverwriteMode());
    \Drupal::logger("reuse bug")->info("is `$destination` a local uri? $local");
    \Drupal::logger("reuse bug")->info("is `$destination` a file? " . is_file($destination));
```
```
 is `private://c9/a0/60/c39365820edc5d1a51f221d49e96a8a730` a local uri? false
 is `private://c9/a0/60/c39365820edc5d1a51f221d49e96a8a730` a file? 1
```
The OverwriteMode is correct.

**Comment by birkland** [comment]
@bseeger  has reason to believe this might work now, follow-up with her to determine why it might start working, and see if it does.

**Comment by birkland** [comment]
Specifically, jhu-idc/idc-isle-dc#193 might fix the underlying problem that prevented this from working, see 

https://github.com/jhu-idc/idc-isle-dc/pull/193/files#diff-8d4ff8d9da3953c42ff432f7627bde82a0aea0463be635261a275366d5173e9dR86 and 

https://github.com/jhu-idc/idc-isle-dc/pull/193/files#diff-48b1c74c53260cecf8edd554615fe9df2743d2b94526f11544d24b38ca318486R79

**Comment by emetsger** [comment]
#310 was created (Apr 6) prior to the merge of [s3](https://github.com/jhu-idc/idc-isle-dc/pull/121) (May 4).  Recall that a consequence of S3 is that it provides a StreamWrapper that takes over the implementation of the `private://` filesystem/url scheme.  The comments/assessment in #310 are obsolete given that S3 was subsequently merged.

---

The **current state** of behaviors in `development` are:
> Note: migration definitions in `development` specify `reuse: false`
1. If a _migration_ specifies the import of multiple byte-for-byte identical bytestreams, like this [migration](https://github.com/jhu-idc/idc-isle-dc/blob/development/tests/10-migration-backend-tests/testcafe/migrations/media-document.csv) does, only one bytestream will be stored in S3.  This is because the migration definition generates filenames based on the sha of the file content.  When a file of the same name already exists, the original file remains unchanged and the duplicate file is discarded.  The end result will be two unique File entities, both referencing the same bytestream (this is verified by `Test_VerifyDuplicateMediaAndFile` in the `10-migration-backend-tests` suite).
![identical-bytestreams](https://user-images.githubusercontent.com/146970/130819532-5e44e02e-84af-4023-ad57-bfc7ae176f58.png)
1. If an _end user_ uploads multiple byte-for-byte identical bytestreams, separate byte streams will be stored.  This is because the UI names the files and specifically avoids filename collisions.  The UI does not consider the content sha when naming files.
![duplicate-bytestreams](https://user-images.githubusercontent.com/146970/130819542-24f64b6a-55b7-44a0-90d5-5967c8a35d32.png)

---

To clarify a couple comments from the IDC meeting yesterday, the motivation for writing #310 was not because there was a _problem_, _per se_.  It was written to solicit any unintended consequences where multiple File entities reference the same bytestream (i.e. the situation illustrated in point 1, above).

**Prior to the [S3 merge](https://github.com/jhu-idc/idc-isle-dc/pull/121)**, setting `reuse: true` parameter of the `file_import` migration process plugin would result in re-using an _existing_ File entity based on the URI to its bytestream.  If a _migration_ specifies the import of multiple byte-for-byte identical bytestreams, like this [migration](https://github.com/jhu-idc/idc-isle-dc/blob/development/tests/10-migration-backend-tests/testcafe/migrations/media-document.csv) does, only one bytestream would be stored, **and** _only a single_ `File` _entity would be created_ (if `reuse: true` is specified).  This is because when the second file was imported, its URI would already be used by the previous File, and so the previous File would be referenced instead of a second File entity being created.

![singlefile-singlebytestream](https://user-images.githubusercontent.com/146970/130820262-f2ac7343-3576-4c1d-ae78-bd7ee0b0eb40.png)

Because the `S3fsStream` does not extend `LocalStream` (this despite the fact that it implements the required abstract methods of `LocalStream`), the behavior of re-using `File` entities is no longer an option (unless we fork a module and update it ourselves).

---

Personally, I see little to no risk exhibited by the current behavior of `development`.  I recommend that the issues relating to this be closed, with no other action required.

However, if there are concerns, then the desired behavior needs to be articulated by someone, and then adjustments can be made.  For example, if the desired behavior is for migrations to behave like the UI does, then `file_import` migration definitions need to be updated to _avoid_ filename collisions rather than explicitly generate them (via shas).

(@birkland @bseeger)

**Comment by birkland** [comment]
Closing this ticket because `reuse: true` has no effect for s3fs
