### ISSUE TITLE
Update migrations to use iid for references by default

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#388]
For referencing entities with a unique id field from within CSVs, configure the `parse_entity_lookup` plugin to use `field_unique_id` as value key, by default, when parsing quads (e.g. `:::iid`)

- [x] update migrations to have the `parse_entity_lookup` and `entity_lookup` processes use `field_unique_id` instead of `title` or `name` as the default for value_key. 
- [x] update test migrations to use the unique_id field information in entity references (to align with first task above).
- [x] ~~update the Export View Field Formatters to use the `field_unique_id` as the default field to export information from when writing out Entity Reference Fields.~~ This will be covered in: https://github.com/jhu-idc/iDC-general/issues/389

**Comment by bseeger** [comment]
Hi @birkland  and @mjanowiecki , 

In the migrations there are a few Entity Reference fields that do not use the `parse_entity_lookup` (quad formatting) - they use the `entity_lookup` process.  `entity_lookup` is similar to `parse_entity_lookup` except that it will only do the look up across one entity type (node or vocabulary) for information - we set this in the migration.  This is because values for that field only come from one vocabulary, so it didn't need the quad setup.  For example, fields like `field_access_rights` only use the Access Rights taxonomy - they don't necessary _need_ the quad structure. 

So, right now some fields use `entity_lookup` (`uid12334`) and some use `parse_entity_lookup` (`:::uid12334`). Would that be confusing for someone creating ingests to have these different formats? 

I'm going to make everything key off of `field_unique_id` (both `parse_entity_lookup` and `entity_lookup`) but am just curious if I should leave the `entity_lookup`s or change them to `parse_entity_lookup`s for consistency's sake.  If I  left the `entity_lookup`s and switch their default lookup key to be `field_unique_id`,  the person writing the ingest CSV will need to know which fields need the `:::` and which do not.  

I could change them all to be `parse_entity_lookup`s, following the same pattern  as all the other `parse_entity_lookup` fields (`:::uid1234` where `field_unique_id` will be the default lookup field). This could be slightly confusing to users as it seems like they could fill in other parts of the quad (`<entity_type>:<bundle>:<value_key>:<value>`), but really the first two parts should not be set to something other than the defaults expected, since the field only uses one vocabulary.  Meaning if we did this with something like `Access Rights`, the fields ingest value might look like this: `:::uid2312`.  Having the `:::` makes it seem like you have more flexibility than you actually do.  Would this be too confusing? 

I think we might have decided that everything should use the `parse_entity_lookup`... but I can't remember clearly. 

Thoughts?  Let me know if you need more information about these.

**Comment by bseeger** [comment]
Looks like we did talk about this on Slack a while back with the thought to leave them as-is for now.   I am going to have to make a pass through all of them to update the value_key (aka lookup field) to use the `field_unique_id` anyways, so it's a good time for me to change this as well, if we had a clear direction to go in.

**Comment by mjanowiecki** [comment]
Hi Bethany, thank you so much for doing this. I think having everything use `parse_entity_lookup` for all of the fields might be simplest? I don't have a super strong opinion, as I think there are pros and cons either way, but it seems like the consistency might make it easier from a troubleshooting perspective. Hopefully folks will be well versed enough on the taxonomies to know when fields accept 1 taxonomy or many.

**Comment by bseeger** [comment]
Thanks, @mjanowiecki. I will change these for consistencies sake. The one spot I don't think I should change are language tags, for fields like Alternative Title, Description, etc.  Those language tags are entity references and looked up by the code there. 

Example Alternative Title:   `Jane Eyre, The Book@eng` 

It seems safe to assume that we won't have duplicate languages and that these can stay as is?

**Comment by mjanowiecki** [comment]
Yep, I think that's safe to assume :)
