### ISSUE TITLE
Investigate SAML2 module for use in supporting SSO with iDC

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#39]
We've confirmed that iDC system will indeed require SSO authentication for privileged users. This ticket covers the tasks of investigating existing I8 module SAML2 in order to implement this requirement.

**Comment by bseeger** [comment]
A potential path for SAML SSO authentication.  We can use this drupal plugin: https://www.drupal.org/project/simplesamlphp_auth. 

The general setup is to put a Service Provide (SP) on the same system as the Drupal install - in this case using SImpleSAMLphp. Configure and setup that up, ensuring that it can talk with an Identity Provider (IdP) on campus.  Once that's done, install the Drupal Simple SAML Auth plugin as well as on called External Auth.  Connect the SAML plugin to the SP and test it out.  

With the SimpleSAML Auth plugin we can setup a rule to associate certain people logging in with certain roles.

**Comment by bseeger** [comment]
To conclude this ticket: 
1. include testing of Collection Level Admin role
1. Task list for use case

**Comment by bseeger** [comment]
### Task List

- System: Install SimpleSamlphp on the server where Islandora 8 is, and set it up as a Service Provider (SP). 
- System: Communicate with central IT to: 
  - Get Identity Providers (IdP) information (URL, metadata file, anything else?)
  - Provide information about the SP so that it will be a trusted source.
- System: Get the SP to talk to the IdP and ensure that that’s happening correctly. 
- System: on SP make some friendly names for EPPN and mail (and anything else needed). Drupal needs friendly names and not oids.
- Drupal: Install plugins on Drupal site (simpleSAMLphp_auth and external_auth). 
- Drupal: Configure SimpleSAMLphp plugin to communicate with Service Provider. 
- Admin/Config/Drupal: Get a list of usernames from Katie (?) that will authenticate in the system, as well as what roles they should have once logged in. 
- Drupal: Create or ensure the Roles necessary exist in the system.
- Drupal: Configure role rules in the SimpleSAMLPlugin to set up users.  
- Drupal: Figure out if we can block users who are not assigned a role from authenticating into the system. Or ensure that the basic authentication role cannot actually do anything more then and non authenticated user. This could be used for restricting access to certain collections at some point. 
- For development environment, all of the above plus add the following steps: 
  - Install a local IdP to test against, maybe in Docker environment
