### ISSUE TITLE
Assess impact of updating to Islandora 2.0.0

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#396]

**Comment by noahwsmith** [comment]
Does I 2.0.0 include this change already? https://github.com/jhu-idc/iDC-general/issues/362

> Change Preservation Master File to Preservation File in Media Use Taxonomy

**Comment by dannylamb** [comment]
Since you're mostly just using the core islandora module and have forked islandora_defaults and controlled_access_terms, you most likely aren't going to experience a ton of disruption.  

The biggest change is that you no longer need Gemini. After the update, everything will continue to function, but you'll have some infrastructure you'll need to clean up.  Firstly, you'll want to drop the container for Gemini in your `docker-compose.yml`.  You'll also have an extra listener running in Alpaca, but it's pretty harmless and easy to turn off in your fork of buildkit. If you were using the community containers, you'd just `docker pull` the new ones and everything would shake out :wink: 

There's a 'batch upload' button that will appear on the children and media tabs that may or may not be worth your while.  They're pretty handy and save a lot of clicks, but I think you'll have conflicts with any required fields you've added above and beyond the ones in islandora_defaults. You may have to alter it out.

If you merge in the new changes from controlled access terms, you'll get indexing improvements for ETDF dates and some bug fixes.  These will require a database update, FYI.

Other than that, maybe the only other thing you'll be interested in is the new `islandora_advanced_search` module, which is a nice boolean search widget that folks find useful.

**Comment by dannylamb** [comment]
> Does I 2.0.0 include this change already? #362

Unfortunately, no.
