### ISSUE TITLE
Test instance:  access denied error when accessing media files that were migrated into system

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#411]
### General 
Note that this only seems to happen with migrated files, not ones uploaded by hand. 

On the test instance @mjanowiecki noticed that while she could ingest pdf files, she could not actually access them once ingested.  

For example, trying to view/get the file for this node:

`https://test.digital.library.jhu.edu/node/80`

 at this URL results in: 

`https://test.digital.library.jhu.edu//system/files/74/5c/b2/08f6fa80943da951ae95a28f40c0d4c8f8`

results in an authorization error. 

We cannot reproduce this behavior locally, so there seems to be something about drupal & S3 on the tests instance that is just different enough to trigger this.  We've confirmed that the files go into S3 okay and that things look good there.  

Adding items by hand seems to work fine. 

### Below are some things we've noticed or seem relevant

The log points to Access Denied Errors with the following message: 
```
Path: /system/files/74/5c/b2/08f6fa80943da951ae95a28f40c0d4c8f8. Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: in Drupal\system\FileDownloadController->download() (line 96 of /var/www/drupal/web/core/modules/system/src/FileDownloadController.php).
```

**Comment by jaredgalanis** [comment]
I'll note that after uninstalling the idc ui module from the test instance we still see the same errors in the recent log messages.

It does appear that the JWT errors we discussed are being thrown [when a file is inaccessible](https://test.digital.library.jhu.edu/admin/reports/dblog/event/200560) AND [when a file is accessible](https://test.digital.library.jhu.edu/admin/reports/dblog/event/200574). 

So I think the [FileDownload error](https://test.digital.library.jhu.edu/admin/reports/dblog/event/200561), which only happens when a file is inaccessible is more likely a symptom of the problem here.

Also, hopefully we can rule out the ui module as being implicated since it shouldn’t be a part of the system as of right now.

**Comment by birkland** [comment]
My working theory is that this is due to #412

**Comment by htpvu** [comment]
Chatted with bethany. no longer an issue.
