### ISSUE TITLE
Derivative Generation Timeouts are expected for large files at scale

### ISSUE THREAD

**Issue by noahwsmith** [jhu-idc/iDC-general#418]
This issue will likely need to be resolve to handle full-scale ingests with large original files:

https://github.com/Islandora/documentation/issues/1896

**Comment by noahwsmith** [comment]
There is now a potential solution in that Issue.

**Comment by noahwsmith** [comment]
I would assign this to @dannylamb if I could, but I can't

**Comment by dannylamb** [comment]
Did a couple hours diving into this, and it's the interplay of a bunch o' things.  I either set, or added logic to set, every nginx and php timeout I could find.

For nginx I did:
- `fastcgi_read_timeout`
- `fastcgi_send_timeout`
- `fastcgi_connect_timeout`
- `proxy_read_timeout`
- `proxy_send_timeout`
- `proxy_connect_timeout`
- `send_timeout`
- `keepalive_timeout`
- `client_body_timeout`
- `lingering_timeout`

For PHP I did:
- `default_socket_timeout`
- `max_execution_time`
- `max_input_time`
- `process_control_timeout`
- `request_terminate_timeout`

It also required me to really really really bump up the timeout values for Alpaca that y'all did in https://github.com/Islandora/Alpaca/pull/79.  Since they're in milliseconds, it needs to be something super duper high like `999999999999`.

This was all done in a fervor to try and make things work, so I'm not sure if it's one, all, or some combination of these settings to do the trick.  But I can at least contribute back the stuff I did to allow us to set all these values.

**Comment by birkland** [comment]
Resolved in https://github.com/jhu-idc/idc-isle-dc/pull/260
