### ISSUE TITLE
Investigate authn from the service to Drupal API.  

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#46]
DO we need to use SAML?  Can we use basic auth or JWT instead?  

more context can be found here https://docs.google.com/document/d/1-fRcHZzXn9h9W0TxJBnFJCI7MV9mElRuwwFNInPotPU/edit#

**Comment by emetsger** [comment]
The short answer is no, we do not need to use SAML.  Basic auth or JWT can be used to authenticate to the Drupal API.

The longer answer is that Drupal's authentication framework can use a session cookie, username/password, or JWT tokens to authenticate requests.  SAML is a means to obtain a session cookie.  So while a service (like ingest) could use SAML to obtain a session cookie for authentication purposes, it would not be necessary as long as the user used by the service can request a JWT or use basic auth.

SimpleSAML works a bit differently than a HTTP reverse proxy configured as a Shibboleth SP.  

The reverse proxy pattern is ideal (or applicable) when the application being protected has no authentication or authorization framework of its own.  However, when an application like Drupal (i.e. one with its own authn/z model) wants to present itself as Shibboleth SP, the reverse proxy pattern isn't very useful.  The notion of "protected paths" becomes nuanced, and is a function of the application's authn/z implementation.  Therefore, in order to function effectively and simultaneously integrate Shibboleth, tighter coupling between the application and Shib is required.  SimpleSAML provides this coupling.

SimpleSAML simply configures and enables the Shibboleth endpoints that participate in the exchange of SAML messages between the IdP and SP.  Once a user is (optionally) created and authorized, SimpleSAML can synchronize Drupal user attributes with Shibboleth user attributes, and assign the user to roles.  But the end result of a SAML login is the production of a Drupal session cookie.
