### ISSUE TITLE
update visual elements related to help tips in advanced seaerch

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#482]
see screenshot for requested changes.
<img width="868" alt="Screen Shot 2022-01-21 at 2 31 20 PM" src="https://user-images.githubusercontent.com/11050142/150589504-e01c7ad2-55d7-4fc0-bfe6-0e4b22984e8a.png">

Additionally update the help text to improve its helpfulness
  * Should specify double quotes (as single quotes does nothing)
  * Many library systems assume a phrase search. We needs to clarify that words / phrases are split up in our searches
  * Include boolean symbols? &&, ||, !

relates to this test scenario https://docs.google.com/document/d/1V7YBFVrQv18QRuEsR4FtRJDGO7-BSd113IsfGuzafgs/edit#

**Comment by jabrah** [comment]
The spacing for the `Search Tips` button label on the (basic) search page is interesting because of the number of inline items.

For reference, the title for the test collection shown in the following screenshots is "`Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu`". A really long title to check how long titles are displayed.

We currently have no button label
![image](https://user-images.githubusercontent.com/5167587/151573018-962187cb-c584-47f0-a0ba-04870250b33a.png)

With the label, we restrict the space for the title by about 80px
![image](https://user-images.githubusercontent.com/5167587/151572974-a96e42eb-1490-4036-b82d-80c8307d3890.png)

![image](https://user-images.githubusercontent.com/5167587/151574327-f5015df0-80bb-4fc2-8a39-0c72d85e26e1.png)

**Comment by jabrah** [comment]
Moving the button to the right of the search input feels a bit better 
![image](https://user-images.githubusercontent.com/5167587/151577365-757955c9-b4ee-401b-bf15-69c1c9084561.png)
