### ISSUE TITLE
Update the receiving email address on the contact us form on the home page

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#490]
upon sending a message on the "contact us" form, we are unsure where the message went.

Messages from this form should go to `[jscholarship-help@jhu.edu](mailto:jscholarship-help@jhu.edu)`

**Comment by jabrah** [comment]
This will need a config change in `idc-isle-dc`.

The easiest way to make the change is in the admin interface: 

`admin > Structure > Contact forms`

Edit the "Website feedback" form, setting the Recipients field to the requested value.

Once the change is made, the configuration will need to be exported and committed to Git so that it can be included in a future release

**Comment by htpvu** [comment]
We need this to be corrected prior to launch. Or else, "contact us" messages sent to admin will be lost.

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-isle-dc/pull/306
