### ISSUE TITLE
Develop process for synching staging with prod

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#78]

**Comment by cyork** [comment]
See [idc-25](https://docs.google.com/document/d/1yjmIjXM1y-9vcDHlTAcagNH3uH9c77vh9fvWRkX3RZ4/edit) and grep for 'sync' to understand the latest syncing requirements.  Right now:

- "The code base of the sandbox instance should be synchronized with what is in production to ensure a seamless transition when staff transition to the production environment. The relevant behaviors, features and look and feel of the sandbox will mimic production. "
- "There should be a way to synchronize the test system to the production system, to be run on an “as needed” basis."
- Data does not need to be in perfect sync with the production server [with the staging server], but there needs to be a method to synchronize the data on an as-needed basis.

Figure out exactly what needs to be sync'd (databases?  content?), and develop a process for doing it in a way that satisfies [IDC-25](https://docs.google.com/document/d/1yjmIjXM1y-9vcDHlTAcagNH3uH9c77vh9fvWRkX3RZ4/edit).

**Comment by jhujasonw** [comment]
Taking a stab at thinking about how this might work:

Things to sync:

1. The database
2. The S3 bucker (for the data linked to the contents of the database)
3. The Solr Index to the data that is linked in the database
4. The image tags of all the container images used in the database (this may be a manual process to make sure they match.)

Thoughts on the process: 

- Sync could be done by a kubernetes Job manifest.   Creating a container that could access the both prod and staging databases, prod and staging s3 and somehow sync the solr index (Can this just be a copy of the solr files?)
- The Job could easily be turned into a Cron manifest so that it ran on a scheduled basis.
- The sync would run in the sandbox instance and maybe have Read Only access to the prod data and database.

Caveats:
- Prod would need to have a way to allow the staging read only access to it's resources.
- This process would be highly destructive to the staging instance.
- If ran in an automated way, anyone using staging would need to realize it could get reset at a certain time (the cron could be halted by OPS if needed)
- What issues could arise if we don't sync the data? (Could images and other media point to a default "thing" if run in staging and resource isn't found?)
- ???

Thoughts @derekbelrose and @birkland ?

**Comment by derekbelrose** [comment]
As staging is not meant for public consumption, I would question the need for a near full data sync. I was told to plan for 10TB and to keep that updated would mean several hours to reset an environment.

What is the goal of having a staging area? If it's functionality testing, can we curate a few examples of each piece of media instead of potentially syncing 10TB?

I am talking about the images, videos and files that are stored in S3.

**Comment by jhujasonw** [comment]
That would be a good idea, only have a few items in stage that are also in prod, and not sync data.  It might also be interesting to not have the instance running if it's not needed, that way the sync could happen on startup and would only be consuming resources when it's needed.  Startup would require OPS intervention, at that point, but *may* be able to be automated.... maybe....

**Comment by birkland** [comment]
As discussed earlier with Michelle, bytestreams (file content) is not needed for launch.  Yes, links will be broken.  But the initial use case for staging does not require file downloads for pre-existing objects to work.  Therefore, db and solr indexes are all that are needed for the time being.  If a later use case presents a need for files, that will be dealt with separately.

**Comment by jhujasonw** [comment]
https://github.com/jhu-idc/idcApp-k8s/issues/85 closed, closing this ticket.
