### ISSUE TITLE
Figure out backup and restore 

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#79]

**Comment by cyork** [comment]
Figure out the key details related to IDC backup and restore:

- What IDC state needs backup (dbs?  volumes?)
- When schedule for backup?
- Figure out technical details for backup and restore.
- Take down production, and restore to verify that it works

**Comment by derekbelrose** [comment]
As far as I am aware, all configuration is managed by overlays or environment variables, so that is not required.

The following states absolutely need to be backed up:
* drupal persistent storage (S3 bucket, can be replicated and versioning can be turned on)
* mariadb databases (drupal_default or whatever the default database is)
* K8s SealedSecrets key

The following can be backed up, but might not be needed:
* SOLR index (can be regenerated, so it might not be needed)

**Comment by derekbelrose** [comment]
Reference for S3 replication:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-walkthrough1.html
https://aws.amazon.com/premiumsupport/knowledge-center/s3-undelete-configuration/

**Comment by derekbelrose** [comment]
https://docs.google.com/document/d/1GbeiqGxr8H8szjXKgeE6CTCAAeZ6X5eCQoXie5lRICk/edit

**Comment by derekbelrose** [comment]
Aaron has read and approved it for normal human consumption.
