### ISSUE TITLE
Create and Populate GitHub repository for the Kubernetes assets

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#84]
Kubernetes manifests, infrastructure automation and other assets that are created for this pilot will be stored here
Expected outcome:
- [x] An initial GitHub repo with directory structure for Kubernetes manifests, kustomize files, terraform automations for infrastructure
- [x] Create an initial README file
- [x] GitHub actions and possible probot integrations

**Comment by jhujasonw** [comment]
Repo created: https://github.com/jhu-sheridan-libraries/idc-kubernetes

It's empty now but I will get some stuff into it today.

**Comment by jhujasonw** [comment]
Put some initial stuff in there, since iDC doesn't have any actual kubernetes artifacts yet, I used a simple web server image to show the service.  It can probably be simplified and such as needed, but it shows the general idea.

There are couple of primer README.md files in there, that can also be updated.

And a terraform format linter is in there.  Stubs exist for the issues2jira setup if/when we want to implement that.

Further CI/CD stuff can be added as needed.

Let me know if this fits with what was needed for this ticket and if it can be closed.

This has not been tested yet, as we are waiting on a new AWS account to be setup for iDC.  I will perform a test deployment of it when that is ready.

**Comment by jhujasonw** [comment]
Example has been deployed to a new iDC AWS Account.

Verified example works.

http://test.idc-kubernetes.cloud.library.jhu.edu/
http://prod.idc-kubernetes.cloud.library.jhu.edu/
http://dev.idc-kubernetes.cloud.library.jhu.edu/
http://graylog.idc-kubernetes.cloud.library.jhu.edu:9000/

Closing ticket.
